# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

squareRootSymmetric <- function(M) {
    .Call('RDeco_squareRootSymmetric', PACKAGE = 'RDeco', M)
}

standardizeVector <- function(V) {
    .Call('RDeco_standardizeVector', PACKAGE = 'RDeco', V)
}

standardizeMatrix <- function(M) {
    .Call('RDeco_standardizeMatrix', PACKAGE = 'RDeco', M)
}

tMatrix <- function(M) {
    .Call('RDeco_tMatrix', PACKAGE = 'RDeco', M)
}

mulMatrices <- function(A, B) {
    .Call('RDeco_mulMatrices', PACKAGE = 'RDeco', A, B)
}

invSymmMatrix <- function(M) {
    .Call('RDeco_invSymmMatrix', PACKAGE = 'RDeco', M)
}

DECO_LASSO_C <- function(Y, X, p, n, lambda, r, ncores = 1L, intercept = TRUE) {
    .Call('RDeco_DECO_LASSO_C', PACKAGE = 'RDeco', Y, X, p, n, lambda, r, ncores, intercept)
}

