---
title: "RDeco Package"
author: Jack Carter, Samuel Davenport, Jeremias Knoblauch, Giulio Morina
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE}
require(RDeco)
require(rbenchmark)
```

## RDeco package

Some coll description should be included here!!

## Speed comparison

```{r data}
set.seed(100)
n<-50
p<-18
m<-4
sigma<-1
lambda<-0.03
r<-0.01
X<-matrix(rnorm(n*p, sd=1), nrow=n)
eps<-rnorm(n, mean = 0, sd = sigma)
activeCoefs<-sample(c(0,1),p, prob=c(0.9, 0.1), replace=TRUE)  ##get coefficients that impact Y
coefs<-activeCoefs*1
Y<-X%*%coefs + eps
ncores <- 8

for (refinement in c(FALSE,TRUE)) {
  res<-DECO_LASSO_R(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement)
  res_mix<-DECO_LASSO_MIX(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement)
  res_C<-as.vector(t(DECO_LASSO_C_PARALLEL(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement)))
  res_C_parallelLasso <- as.vector(t(DECO_LASSO_C_PARALLEL(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement, parallel_lasso = TRUE)))
  res_C_gradientdescent <- as.vector(t(DECO_LASSO_C_PARALLEL(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement, glmnet = FALSE)))
  if(all.equal(res,res_mix) == TRUE && all.equal(res,res_C) == TRUE && all.equal(res_C,res_C_parallelLasso) == TRUE) {
    print("All functions return the same result!")
  } else {
    print("NOT all functions return the same result...")
  }
  print(benchmark(DECO_LASSO_R(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement),
            DECO_LASSO_MIX(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement),
            DECO_LASSO_C_PARALLEL(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement),
            DECO_LASSO_C_PARALLEL(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement, parallel_lasso = TRUE),
            replications = 10, order="relative"))

}

#Bigger dataset
n<-1000
p<-10000
m<-8
X<-matrix(rnorm(n*p, sd=1), nrow=n)
eps<-rnorm(n, mean = 0, sd = sigma)
activeCoefs<-sample(c(0,1),p, prob=c(0.9, 0.1), replace=TRUE)  ##get coefficients that impact Y
coefs<-activeCoefs*1
Y<-X%*%coefs + eps
for (refinement in c(FALSE,TRUE)) {
  print(benchmark(DECO_LASSO_C_PARALLEL(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement),
              DECO_LASSO_C_PARALLEL(Y, X, p=p, n=n, m=m, lambda=lambda, r_1=r, ncores = ncores, refinement = refinement, parallel_lasso = TRUE),
              replications = 5, order="relative"))
}
```


